<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.14.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\POS.Domain\POS.Domain.csproj" />
    <ProjectReference Include="..\POS.Utilities\POS.Utilities.csproj" />
  </ItemGroup>

</Project>
